version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks: 
      - rabbitmq_net
    volumes:
      - ./RabbitMQ/data/:/var/lib/rabbitmq/
      - ./RabbitMQ/log/:/var/log/rabbitmq/
  pgdb_orders: 
    image: postgres
    container_name:  pgdb_orders
    volumes: 
      - ./OrderService/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5433"
    ports:
      - "5433:5432"
    environment: 
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgdb_users: 
    image: postgres
    container_name:  pgdb_users
    volumes: 
      - ./UserService/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5434"
    ports:
      - "5434:5432"
    environment: 
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  orders:
    build: ./OrderService
    container_name: order_service
    volumes:
      - ./OrderService:/usr/src/app
    ports:
      - "8000:8000"
    depends_on: 
      - pgdb_orders
      - rabbitmq
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
  users:
    build: ./UserService
    container_name: users_service
    volumes:
      - ./UserService:/usr/src/app
    ports:
      - "8001:8001"
    depends_on: 
      - pgdb_users
      - rabbitmq
    command: bash -c "python manage.py runserver 0.0.0.0:8001"

networks: 
  rabbitmq_net:
    driver: bridge