version: "3.7"

services:
  django:
    build: .
    container_name: order_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on: 
      - pgdb
  pgdb: 
    image: postgres
    container_name:  pgdb
    environment: 
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres