# Generated by Django 3.1.7 on 2021-03-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderapi.location')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INIT', 'Order Created'), ('ASSIGNED', 'Order assigned to courier'), ('PICKUP', 'Order picked up by courier'), ('COMPLETED', 'Order completed'), ('CANCELED', 'Order was canceled')], default='INIT', max_length=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orderapi.client')),
                ('order_txt', models.CharField(max_length=100)),
                ('pick_up_description', models.CharField(max_length=100, null=True)),
                ('pick_up_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderapi.location')),
            ],
        ),
    ]
