# Generated by Django 3.0 on 2021-05-06 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=256)),
                ('street_number', models.CharField(default='', max_length=256)),
                ('postal_code', models.CharField(default='', max_length=256)),
                ('city', models.CharField(default='', max_length=256)),
                ('region', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_txt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapi.Address'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
