# Generated by Django 3.0 on 2021-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0002_auto_20210506_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
