# Generated by Django 3.0 on 2021-05-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0003_order_courier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_number',
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_location', to='orderapi.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_location', to='orderapi.Address'),
        ),
    ]
