# Generated by Django 3.0 on 2021-05-26 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('username', models.CharField(default='', max_length=256, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256, unique=True)),
                ('password', models.CharField(default='', max_length=256)),
                ('phone_number', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=256, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256, unique=True)),
                ('password', models.CharField(default='', max_length=256)),
                ('phone_number', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
