# Generated by Django 3.2 on 2021-04-21 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=100)),
                ('street_number', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=257)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
        ),
    ]
