# Generated by Django 3.2 on 2021-05-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basicuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicuser',
            old_name='surname',
            new_name='last_name',
        ),
    ]
