# Generated by Django 3.2 on 2021-05-02 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_surname_basicuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=257)),
                ('phone_number', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('courier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.courier')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
            ],
            bases=('users.courier',),
        ),
        migrations.DeleteModel(
            name='BasicUser',
        ),
    ]
